name: Ruby

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    services:
      whoami:
        image: containous/whoami
        ports:
          - 80